### ISSUE TITLE
Icon and job shorthand for self injected in the wrong spot

### ISSUE THREAD

**Issue by Dranni21312** [Pilzinsel64/PlayerTags#9] opened 2022-09-02 07:49 UTC
As shown below, the [DPS] RDM decorator for self (white rectangle) is injected in the incorrect spot:

![image](https://user-images.githubusercontent.com/80227585/188085902-5534fc59-4bc2-4355-8afc-89b65b4819aa.png)

For everyone else in the chat, the party / alliance marker comes after the icon/job name. For self, the party / alliance marker comes first.

**Comment by Pilzinsel64** [comment] 2022-09-02 09:23
Duplicate of #6.
See this comment. The only quick and dirty solution would be to completly remove the number and create a full custom payload with it's name. But that could also break other plugins as you mentoined in #8.

**Closed by Pilzinsel64** 2022-09-02 09:23 UTC
Labels: duplicate
